version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: UTC
    open-pull-requests-limit: 1
    commit-message:
      prefix: "[Dependabot]"
    labels:
      - dependencies
      - rust
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: UTC
    open-pull-requests-limit: 1
    commit-message:
      prefix: "[Dependabot]"
    labels:
      - dependencies
      - github-actions
